USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS MONITORING_DB;
CREATE SCHEMA IF NOT EXISTS MONITORING_DB.QUALITY_METRICS;

CREATE OR REPLACE DATA METRIC FUNCTION MONITORING_DB.QUALITY_METRICS.INVALID_PESEL_COUNT (
    ARG_TABLE TABLE (PESEL VARCHAR)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*)
    FROM ARG_TABLE
    WHERE PESEL IS NULL 
      OR NOT (REGEXP_LIKE(PESEL, '^[0-9]{11}$')) OR PESEL = '00000000000'
$$;

USE SGH;
-- Ustawienie harmonogramu sprawdzania dla całej bazy/schematu
ALTER TABLE BAZA_KLIENTOW_WWW SET DATA_METRIC_SCHEDULE = '5 MINUTE';


SELECT MONITORING_DB.QUALITY_METRICS.INVALID_PESEL_COUNT(
  SELECT PESEL FROM SGH.PUBLIC.BAZA_KLIENTOW_WWW
);

-- select PESEL, count(*) from baza_klientow_www group by 1 order by 2 desc;

-- Przypisanie funkcji do konkretnej kolumny
ALTER TABLE BAZA_KLIENTOW_WWW ADD DATA METRIC FUNCTION MONITORING_DB.QUALITY_METRICS.INVALID_PESEL_COUNT ON (PESEL);

SELECT *
  FROM TABLE(SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS(
    REF_ENTITY_NAME => 'SGH.PUBLIC.BAZA_KLIENTOW_WWW',
    REF_ENTITY_DOMAIN => 'table'));

-- Lista DMF w konkretnym miejscu
SHOW DATA METRIC FUNCTIONS IN SCHEMA MONITORING_DB.QUALITY_METRICS;

SHOW PARAMETERS LIKE 'DATA_METRIC_SCHEDULE%' IN TABLE SGH.PUBLIC.BAZA_KLIENTOW_WWW;

SELECT *
FROM TABLE(INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
    REF_ENTITY_NAME => 'SGH.PUBLIC.BAZA_KLIENTOW_WWW',
    REF_ENTITY_DOMAIN => 'TABLE'
));

-- Posiada opóźnienie 
SELECT 
    POLICY_NAME AS DMF_NAME,
    REF_DATABASE_NAME AS DB,
    REF_SCHEMA_NAME AS SCHEMA,
    REF_ENTITY_NAME AS TABLE_NAME,
    REF_ARG_COLUMN_NAMES AS COLUMN_NAME,
    POLICY_STATUS AS STATUS
FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
WHERE POLICY_KIND = 'DATA_METRIC_FUNCTION';


-- ALTER TABLE SGH.PUBLIC.BAZA_KLIENTOW SET DATA_METRIC SCHEDULE = '1440 MINUTE';

-- ALTER TABLE SGH.PUBLIC.BAZA_KLIENTOW_WWW DROP DATA METRIC FUNCTION
--   MONITORING_DB.QUALITY_METRICS.INVALID_PESEL_COUNT ON (PESEL);
